Development (#21)
* test purge in staging pipes (#9)

* clean up old images (#11)

* Feature/cleanupartifacts (#14)

* clean up old images

* +

* Feature/databases (#15)

* test create cloud database

* +

* +

* +

* +

* +

* tear down

* +

* +

* setup and teardown test

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* added migration

* +

* +

* +

* +

* +

* adding problematic collision test

* +

* +

* +

* +

* +

* Feature/database collision test (#16)

* test create cloud database

* +

* +

* +

* +

* +

* tear down

* +

* +

* setup and teardown test

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* added migration

* +

* +

* +

* +

* +

* adding problematic collision test

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* +

* Feature/migrations (#17)

* remove unused migrations, and tidy space

* added check migration on merge, clean up from previous branches

* +

* +

* simulating problematic commit (#18)

* simulating problematic commit

* +

* +

* +

* +

* this should cause problems

* this should work now

* Feature/migrations (#19)

* remove unused migrations, and tidy space

* added check migration on merge, clean up from previous branches

* +

* +

* +

* +

* Feature/rollbacks (#20)

* updated migrations to staging

* testing a migration

* updated staging migrations to avoid deprecation

* mod

* 2 successful migrations, fail migration, successful migration test

* +

* enhanced cicd

* +

* +

* +

* +

* +

* +

* here goes nothing

* +

* +

* test after removing broken migrations

* test mig

* testing pipes

* +

* test

* +

* better backups

* better install of migrate cli

* +

* updated migrate cli install

* testing better backups

* updating pipes

* testing teradown-staging.yml

* +

* testing cleanup scripts

* quiet mode

* updatet url

* +

* added cleanup scripts

* +

* +

* +

* +

* +

* +

* +

* +

* +

* fix sheffessions

* tidy up

* +

diff --git a/.github/workflows/sheffessions-development.yml b/.github/workflows/sheffessions-development.yml
--- a/.github/workflows/sheffessions-development.yml
+++ b/.github/workflows/sheffessions-development.yml
@@ -7,7 +7,100 @@ on:
     ]
 
 jobs:
+  check-migrations-before-merge:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+
+    - name: Check for migration filename prefix collisions against development
+      working-directory: ./backend/sheffessions_api
+      run: |
+        # Explicitly fetch the development branch
+        git fetch origin development
+        # Get the list of all migration prefixes in the PR (i.e., current branch)
+        pr_migrations_prefixes=$(ls db/migrations | cut -d'_' -f1 | sort | uniq)
+        # Get the list of all migration prefixes in development
+        development_migrations_prefixes=$(git ls-tree -r origin/development --name-only db/migrations | cut -d'_' -f1 | sort | uniq)
+        # Compare the migration prefixes from your PR with those in development
+        for prefix in $pr_migrations_prefixes; do
+          if echo "$development_migrations_prefixes" | grep -q "^${prefix}$"; then
+            echo "Collision detected for migration prefix: $prefix"
+            echo "Please update your migration script to avoid conflicts with the development branch."
+            exit 1
+          fi
+        done
+
+        echo "No migration prefix collisions detected."
+
+    - name: Check for migration filename prefix collisions within the same commit
+      working-directory: ./backend/sheffessions_api
+      run: |
+        # Step 1: Extract all prefixes for up and down migrations
+        up_migrations=$(ls db/migrations | grep ".up.sql" | cut -d'_' -f1 | sort)
+        down_migrations=$(ls db/migrations | grep ".down.sql" | cut -d'_' -f1 | sort)
+
+        # Step 2: Ensure matching pairs for every up migration
+        for prefix in $up_migrations; do
+          if ! echo "$down_migrations" | grep -q "^${prefix}$"; then
+            echo "Missing .down.sql migration for prefix: $prefix"
+            exit 1
+          fi
+        done
+
+        # Step 3: Check for any true duplicates
+        all_migrations=$(ls db/migrations | cut -d'_' -f1 | sort | uniq)
+        for prefix in $all_migrations; do
+          count=$(ls db/migrations | grep "^${prefix}_" | wc -l)
+          if [ "$count" -gt 2 ]; then
+            echo "Collisions detected for migration prefix: $prefix"
+            echo "More than one set of .up.sql and .down.sql files share the same prefix within the same commit."
+            exit 1
+          fi
+        done
+
+        echo "No migration prefix collisions detected within the same commit."
+
+  check-migrations-on-merge:
+    needs: [ check-migrations-before-merge ]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+
+    - name: Check for migration filename prefix collisions post-merge
+      working-directory: ./backend/sheffessions_api
+      run: |
+        # Explicitly fetch the development branch
+        git fetch origin development
+        # Check if branches have a common base
+        merge_base=$(git merge-base HEAD origin/development)
+        if [ -z "$merge_base" ]; then
+          echo "The branches have unrelated histories. This can cause issues during merge."
+          exit 1
+        fi
+        # Try merging development into the current branch (simulate what will happen post-merge)
+        git merge origin/development --no-commit --no-ff --allow-unrelated-histories
+        # Get the list of all migration prefixes post-merge
+        merged_migrations_prefixes=$(ls db/migrations | cut -d'_' -f1 | sort | uniq)
+        # Check for duplicates (collisions) within the merged list itself
+        duplicates=$(echo "$merged_migrations_prefixes" | uniq -d)
+        # If there are duplicates, flag them
+        if [[ ! -z "$duplicates" ]]; then
+          echo "Collisions detected for migration prefixes post-merge:"
+          echo "$duplicates"
+          echo "Please update your migration script to avoid conflicts post-merge."
+          exit 1
+        fi
+        echo "No migration prefix collisions detected post-merge."
+
   unit-test-sheffessions_api:
+    needs: [
+      check-migrations-before-merge,
+      check-migrations-on-merge
+    ]
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -29,6 +122,10 @@ jobs:
       run: go test -v *_unit_test.go
 
   unit-test-frontend:
+    needs: [
+      check-migrations-before-merge,
+      check-migrations-on-merge
+    ]
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -63,6 +160,23 @@ jobs:
       unit-test-frontend
     ]
     runs-on: ubuntu-latest
+    env:
+      POSTGRESQL_URL: postgres://postgres_user:mysecretpassword@localhost:5432/devdb?sslmode=disable&search_path=public
+    services:
+      postgres:
+        image: postgres:latest
+        env:
+          POSTGRES_USER: postgres_user
+          POSTGRES_PASSWORD: mysecretpassword
+          POSTGRES_DB: devdb
+        ports:
+          - 5432:5432
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -78,9 +192,6 @@ jobs:
         working-directory: ./backend/sheffessions_api
         run: go get -v ./...
 
-      # Setup MySQL database here
-
-      # Cache pnpm modules
       - name: Cache node modules
         uses: actions/cache@v3
         with:
@@ -95,6 +206,23 @@ jobs:
       - name: Install dependencies
         working-directory: ./frontend/sheffessions
         run: pnpm install
+
+      - name: Wait for PostgreSQL to be ready
+        run: |
+          for i in {1..30}; do
+            if pg_isready -h localhost -U postgres_user; then
+              break
+            fi
+            echo "Waiting for PostgreSQL to be ready..."
+            sleep 1
+          done
+
+      - name: 'Install Migrate CLI'
+        run: curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz && mv migrate.linux-amd64 /usr/local/bin/migrate
+
+      - name: 'Run Migrations'
+        working-directory: ./backend/sheffessions_api
+        run: migrate -database ${POSTGRESQL_URL} -path db/migrations up
 
       - name: Build and Run sheffessions_api
         working-directory: ./backend/sheffessions_api
@@ -120,5 +248,3 @@ jobs:
       - name: Shutdown Backend
         if: always()
         run: pkill server
-
-
diff --git a/.github/workflows/sheffessions-staging.yml b/.github/workflows/sheffessions-staging.yml
--- a/.github/workflows/sheffessions-staging.yml
+++ b/.github/workflows/sheffessions-staging.yml
@@ -4,7 +4,6 @@ on:
   pull_request:
     branches: [ 
       "staging",
-      "main"
     ]
 
 jobs:
@@ -64,9 +63,49 @@ jobs:
       unit-test-frontend
     ]
     runs-on: ubuntu-latest
+    env:
+      POSTGRESQL_PASSWORD_STAGING: ${{ secrets.POSTGRESQL_PASSWORD_STAGING }}
+      POSTGRESQL_URL: postgres://postgres:${{ secrets.POSTGRESQL_PASSWORD_STAGING }}@localhost:5432/postgres?sslmode=disable
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
+      - id: 'auth'
+        uses: 'google-github-actions/auth@v1'
+        with:
+          credentials_json: '${{ secrets.GCP_CREDENTIALS_STAGING }}'
+
+      - name: 'Set up Cloud SDK'
+        uses: 'google-github-actions/setup-gcloud@v1'
+
+      - name: 'Use gcloud CLI'
+        run: 'gcloud info'
+
+      - name: 'Check Instance on Cloud SQL exists and update db password'
+        run: |
+          INSTANCE_EXISTS=$(gcloud sql instances list --filter="name:sheffessions-staging-postgresql" --format="get(name)")
+
+          if [[ -z "$INSTANCE_EXISTS" ]]; then
+            gcloud sql instances create sheffessions-staging-postgresql \
+              --project=sheffessions-staging \
+              --database-version=POSTGRES_15 \
+              --tier=db-f1-micro \
+              --region=europe-west2 \
+              --availability-type=zonal \
+              --storage-type=SSD \
+              --storage-size=10 \
+              --storage-auto-increase \
+              --backup \
+              --backup-start-time=04:00 \
+              --require-ssl
+
+            gcloud sql users set-password postgres --instance=sheffessions-staging-postgresql --password=${POSTGRESQL_PASSWORD_STAGING}
+          else
+            echo "Instance sheffessions-staging-postgresql already exists."
+            echo "Skipping creation." 
+            echo "Updating password to POSTGRESQL_PASSWORD_STAGING"
+            gcloud sql users set-password postgres --instance=sheffessions-staging-postgresql --password=${POSTGRESQL_PASSWORD_STAGING}
+          fi
 
       - name: Setup Go
         uses: actions/setup-go@v3
@@ -79,9 +118,6 @@ jobs:
         working-directory: ./backend/sheffessions_api
         run: go get -v ./...
 
-      # Setup MySQL database here and run migrations against real staging db
-
-      # Cache pnpm modules
       - name: Cache node modules
         uses: actions/cache@v3
         with:
@@ -97,21 +133,111 @@ jobs:
         working-directory: ./frontend/sheffessions
         run: pnpm install
 
-      - name: Build and Run sheffessions_api
+      - name: 'Construct POSTGRESQL_URL and Run sheffessions_api'
         working-directory: ./backend/sheffessions_api
         run: |
+          wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
+          chmod +x cloud_sql_proxy
+          ./cloud_sql_proxy -instances=sheffessions-staging:europe-west2:sheffessions-staging-postgresql=tcp:5432 &
+
+          echo "Waiting for Cloud SQL Proxy to be up..."
+          for i in {1..30}; do
+            if netstat -an | grep "5432" > /dev/null; then
+              echo "Cloud SQL Proxy started!"
+              break
+            fi
+            sleep 1
+          done
+
           go build -o server main.go
           ./server &
 
-      - name: Wait for Backend to Start
+          sleep 10
+
+      - name: 'Install Migrate CLI'
         run: |
-          while ! curl -s localhost:8080 > /dev/null; do
-            sleep 5
+          curl -L -o migrate.linux-amd64.tar.gz https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
+          CHECKSUM="b92fe73d3fc9ea2bd1e02c5b7840c16268e78956c0c05f6bdb90a78c42637020"
+          echo "$CHECKSUM  migrate.linux-amd64.tar.gz" | sha256sum --check
+          if [[ $? -ne 0 ]]; then
+            echo "Checksum verification failed!"
+            exit 1
+          fi
+          tar xvz -f migrate.linux-amd64.tar.gz
+          mv migrate.linux-amd64 /usr/local/bin/migrate
+
+      - name: Backup PostgreSQL Database
+        run: |
+          TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)  # store current UTC timestamp
+          gcloud sql backups create --instance=sheffessions-staging-postgresql
+          echo "BACKUP_TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
+
+      - name: List Backups for PostgreSQL Database
+        run: |
+          RETRY_COUNT=0
+          MAX_RETRIES=5
+          SLEEP_DURATION=30
+          while [[ -z "$BACKUP_ID" && $RETRY_COUNT -lt $MAX_RETRIES ]]; do
+            BACKUP_ID=$(gcloud sql backups list --instance=sheffessions-staging-postgresql --filter="startTime>'$BACKUP_TIMESTAMP'" --sort-by="~creationTimestamp" --limit=1 --format="get(id)")
+            if [[ -z "$BACKUP_ID" ]]; then
+              echo "Backup not found for attempt $((RETRY_COUNT+1)). Retrying in $SLEEP_DURATION seconds..."
+              sleep $SLEEP_DURATION
+              ((RETRY_COUNT++))
+            fi
           done
+
+          if [[ -z "$BACKUP_ID" ]]; then
+            echo "Error: No backup found that was created after $BACKUP_TIMESTAMP after $MAX_RETRIES attempts"
+            exit 1
+          fi
+
+          echo "BACKUP_ID=$BACKUP_ID" >> $GITHUB_ENV
+
+      - name: List Migrations
+        working-directory: ./backend/sheffessions_api
+        run: |
+          echo "MIGRATIONS_LIST=$(find db/migrations -name '*.up.sql' | grep -E '^[0-9]{6}_.+\.up\.sql$' | sort | tr '\n' ';')" >> $GITHUB_ENV
+
+      - name: Apply Migrations Iteratively
+        working-directory: ./backend/sheffessions_api
+        run: |
+          psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
+          IFS=';' read -ra MIGRATIONS <<< "$MIGRATIONS_LIST"
+          if [[ -z "${MIGRATIONS[*]}" ]]; then
+            echo "No migrations to apply."
+            exit 0
+          fi
+          for migration in "${MIGRATIONS[@]}"; do
+            if [[ $migration == *".up.sql" ]]; then
+              echo "==== Applying migration: $migration ===="
+              migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
+              if [ $? -ne 0 ]; then
+                echo "Migration $migration failed. Rolling back..."
+                migrate -database ${POSTGRESQL_URL} -path db/migrations down 1
+                exit 1
+              fi
+            fi
+          done
+
+      - name: Check Database State
+        if: failure()
+        working-directory: ./backend/sheffessions_api
+        run: |
+          echo "Checking if the database is in a dirty state"
+          DIRTY_STATE=$(psql ${POSTGRESQL_URL} -t -c "SELECT dirty FROM schema_migrations WHERE dirty = true LIMIT 1")
+          if [[ "$DIRTY_STATE" == "true" ]]; then
+            echo "The database is in a dirty state!"
+            # We only restore automatically in staging. This can be uncommented in an emergency
+            gcloud sql backups restore $BACKUP_ID --restore-instance=sheffessions-staging-postgresql
+            exit 1
+          fi
+          echo "Database is in a clean state."
+
 
       - name: Run sheffessions_api Integration Tests
         working-directory: ./backend/sheffessions_api
-        run: go test -v *_integration_test.go
+        run: |
+          go test -v *_integration_test.go
 
       - name: Run Frontend Integration Tests
         working-directory: ./frontend/sheffessions
@@ -142,24 +268,19 @@ jobs:
       - name: 'Use gcloud CLI'
         run: 'gcloud info'
 
-      # Configure Docker to use gcloud command-line tool as a credential helper for Artifact Registry
       - name: 'Configure Docker for Artifact Registry'
         run: |
           gcloud --quiet auth configure-docker europe-docker.pkg.dev
 
-      # Generate the image tag combining the commit hash and timestamp
       - name: Generate image tag
         id: generate_tag
         run: |
           echo "IMAGE_TAG_SHEFFESSIONS_API_STAGING=${GITHUB_SHA}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
 
-      # Build and push the Docker image using the generated tag
       - name: 'Build and push Docker image'
         working-directory: ./backend/sheffessions_api
         run: |
           docker build \
-            --build-arg MYSQL_DATABASE_STAGING=${{ secrets.MYSQL_DATABASE_STAGING }} \
-            --build-arg MYSQL_ROOT_PASSWORD_STAGING=${{ secrets.MYSQL_ROOT_PASSWORD_STAGING }} \
             -t europe-docker.pkg.dev/sheffessions-staging/sheffessions-docker-repository/sheffessions_api_staging:sheffessions_api_staging-${{ steps.generate_tag.outputs.image_tag_sheffessions_api_staging }} .
           docker push europe-docker.pkg.dev/sheffessions-staging/sheffessions-docker-repository/sheffessions_api_staging:sheffessions_api_staging-${{ steps.generate_tag.outputs.image_tag_sheffessions_api_staging }}
 
@@ -183,18 +304,15 @@ jobs:
       - name: 'Use gcloud CLI'
         run: 'gcloud info'
 
-      # Configure Docker to use gcloud command-line tool as a credential helper for Artifact Registry
       - name: 'Configure Docker for Artifact Registry'
         run: |
           gcloud --quiet auth configure-docker europe-docker.pkg.dev
 
-      # Generate the image tag combining the commit hash and timestamp
       - name: Generate image tag
         id: generate_tag
         run: |
           echo "IMAGE_TAG_SHEFFESSIONS_FE_STAGING=${GITHUB_SHA}-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
 
-      # Build and push the Docker image using the generated tag
       - name: 'Build and push Docker image'
         working-directory: ./frontend/sheffessions
         run: |
@@ -204,8 +322,10 @@ jobs:
           docker push europe-docker.pkg.dev/sheffessions-staging/sheffessions-docker-repository/sheffessions_fe_staging:sheffessions_fe_staging-${{ steps.generate_tag.outputs.image_tag_sheffessions_fe_staging }}
 
   staging-deploy-sheffessions_api:
-    needs: staging-build-sheffessions_api
+    needs: [ staging-build-sheffessions_api, staging-build-sheffessions_fe ]
     runs-on: ubuntu-latest
+    env:
+      POSTGRESQL_URL: postgres://postgres:${{ secrets.POSTGRESQL_PASSWORD_STAGING }}@/postgres?host=/cloudsql/sheffessions-staging:europe-west2:sheffessions-staging-postgresql&sslmode=disable&search_path=public
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -221,7 +341,6 @@ jobs:
       - name: 'Use gcloud CLI'
         run: 'gcloud info'
 
-      # Deploy to Cloud Run using the generated image tag
       - name: 'Deploy to Cloud Run (API)'
         run: |
           gcloud run deploy sheffessions-api-staging \
@@ -233,10 +352,12 @@ jobs:
             --memory=128Mi \
             --cpu=1 \
             --timeout=300s \
-            --concurrency=80
-
+            --concurrency=80 \
+            --add-cloudsql-instances=sheffessions-staging:europe-west2:sheffessions-staging-postgresql \
+            --set-env-vars=POSTGRESQL_URL=${POSTGRESQL_URL}
+  
   staging-deploy-sheffessions_fe:
-    needs: staging-build-sheffessions_fe
+    needs: [ staging-build-sheffessions_api, staging-build-sheffessions_fe ]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -253,7 +374,6 @@ jobs:
       - name: 'Use gcloud CLI'
         run: 'gcloud info'
 
-      # Deploy to Cloud Run using the generated image tag
       - name: 'Deploy to Cloud Run (API)'
         run: |
           gcloud run deploy sheffessions-fe-staging \
diff --git a/.github/workflows/sheffessions.yml b/.github/workflows/sheffessions.yml
--- a/.github/workflows/sheffessions.yml
+++ b/.github/workflows/sheffessions.yml
@@ -80,10 +80,95 @@ jobs:
             -t europe-docker.pkg.dev/sheffessions/sheffessions-docker-repository/sheffessions_fe:sheffessions_fe-${{ steps.generate_tag.outputs.image_tag_sheffessions_fe}} .
           docker push europe-docker.pkg.dev/sheffessions/sheffessions-docker-repository/sheffessions_fe:sheffessions_fe-${{ steps.generate_tag.outputs.image_tag_sheffessions_fe }}
 
-  production-deploy-sheffessions_api:
+  production-database-migrations:
+    runs-on: ubuntu-latest
     needs: [
       production-build-sheffessions_api,
       production-build-sheffessions_fe
+    ]
+    steps:
+      - name: 'Install Migrate CLI'
+        run: |
+          curl -L -o migrate.linux-amd64.tar.gz https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
+          CHECKSUM="b92fe73d3fc9ea2bd1e02c5b7840c16268e78956c0c05f6bdb90a78c42637020"
+          echo "$CHECKSUM  migrate.linux-amd64.tar.gz" | sha256sum --check
+          if [[ $? -ne 0 ]]; then
+            echo "Checksum verification failed!"
+            exit 1
+          fi
+          tar xvz -f migrate.linux-amd64.tar.gz
+          mv migrate.linux-amd64 /usr/local/bin/migrate
+
+      - name: Backup PostgreSQL Database
+        run: |
+          TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)  # store current UTC timestamp
+          gcloud sql backups create --instance=sheffessions-postgresql
+          echo "BACKUP_TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
+
+      - name: List Backups for PostgreSQL Database
+        run: |
+          RETRY_COUNT=0
+          MAX_RETRIES=5
+          SLEEP_DURATION=30
+          while [[ -z "$BACKUP_ID" && $RETRY_COUNT -lt $MAX_RETRIES ]]; do
+            BACKUP_ID=$(gcloud sql backups list --instance=sheffessions-postgresql --filter="startTime>'$BACKUP_TIMESTAMP'" --sort-by="~creationTimestamp" --limit=1 --format="get(id)")
+            if [[ -z "$BACKUP_ID" ]]; then
+              echo "Backup not found for attempt $((RETRY_COUNT+1)). Retrying in $SLEEP_DURATION seconds..."
+              sleep $SLEEP_DURATION
+              ((RETRY_COUNT++))
+            fi
+          done
+
+          if [[ -z "$BACKUP_ID" ]]; then
+            echo "Error: No backup found that was created after $BACKUP_TIMESTAMP after $MAX_RETRIES attempts"
+            exit 1
+          fi
+
+          echo "BACKUP_ID=$BACKUP_ID" >> $GITHUB_ENV
+
+      - name: List Migrations
+        working-directory: ./backend/sheffessions_api
+        run: |
+          echo "MIGRATIONS_LIST=$(find db/migrations -name '*.up.sql' | grep -E '^[0-9]{6}_.+\.up\.sql$' | sort | tr '\n' ';')" >> $GITHUB_ENV
+
+      - name: Apply Migrations Iteratively
+        working-directory: ./backend/sheffessions_api
+        run: |
+          psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
+          IFS=';' read -ra MIGRATIONS <<< "$MIGRATIONS_LIST"
+          if [[ -z "${MIGRATIONS[*]}" ]]; then
+            echo "No migrations to apply."
+            exit 0
+          fi
+          for migration in "${MIGRATIONS[@]}"; do
+            if [[ $migration == *".up.sql" ]]; then
+              echo "==== Applying migration: $migration ===="
+              migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
+              if [ $? -ne 0 ]; then
+                echo "Migration $migration failed. Rolling back..."
+                migrate -database ${POSTGRESQL_URL} -path db/migrations down 1
+                exit 1
+              fi
+            fi
+          done
+
+      - name: Check Database State
+        if: failure()
+        working-directory: ./backend/sheffessions_api
+        run: |
+          echo "Checking if the database is in a dirty state"
+          DIRTY_STATE=$(psql ${POSTGRESQL_URL} -t -c "SELECT dirty FROM schema_migrations WHERE dirty = true LIMIT 1")
+          if [[ "$DIRTY_STATE" == "true" ]]; then
+            echo "The database is in a dirty state!"
+            exit 1
+          fi
+          echo "Database is in a clean state."
+
+  production-deploy-sheffessions_api:
+    needs: [
+      production-build-sheffessions_api,
+      production-build-sheffessions_fe,
+      production-database-migrations
     ]
     runs-on: ubuntu-latest
     steps:
