+

diff --git a/.github/workflows/sheffessions-staging.yml b/.github/workflows/sheffessions-staging.yml
--- a/.github/workflows/sheffessions-staging.yml
+++ b/.github/workflows/sheffessions-staging.yml
@@ -176,23 +176,6 @@ jobs:
         run: |
           echo "MIGRATIONS_LIST=$(ls db/migrations | sort | tr '\n' ';')" >> $GITHUB_ENV
 
-      # - name: Apply Migrations Iteratively Production
-      #   working-directory: ./backend/sheffessions_api
-      #   run: |
-      #     IFS=';' read -ra MIGRATIONS <<< "$MIGRATIONS_LIST"
-      #     for migration in "${MIGRATIONS[@]}"; do
-      #       # Only apply up migrations
-      #       if [[ $migration == *".up.sql" ]]; then
-      #         psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
-      #         migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
-      #         if [ $? -ne 0 ]; then
-      #           echo "Migration $migration failed. Rolling back..."
-      #           migrate -database ${POSTGRESQL_URL} -path db/migrations down 1
-      #           exit 1
-      #         fi
-      #       fi
-      #     done
-
       - name: Apply Migrations Iteratively
         working-directory: ./backend/sheffessions_api
         run: |
@@ -203,12 +186,29 @@ jobs:
               psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
               migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
               if [ $? -ne 0 ]; then
-                echo "Migration $migration failed. Resetting the database..."
-                gcloud sql backups restore $BACKUP_ID --restore-instance=sheffessions-staging-postgresql
+                echo "Migration $migration failed. Rolling back..."
+                migrate -database ${POSTGRESQL_URL} -path db/migrations down 1
                 exit 1
               fi
             fi
           done
+
+      # - name: Apply Migrations Iteratively
+      #   working-directory: ./backend/sheffessions_api
+      #   run: |
+      #     IFS=';' read -ra MIGRATIONS <<< "$MIGRATIONS_LIST"
+      #     for migration in "${MIGRATIONS[@]}"; do
+      #       # Only apply up migrations
+      #       if [[ $migration == *".up.sql" ]]; then
+      #         psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
+      #         migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
+      #         if [ $? -ne 0 ]; then
+      #           echo "Migration $migration failed. Resetting the database..."
+      #           gcloud sql backups restore $BACKUP_ID --restore-instance=sheffessions-staging-postgresql
+      #           exit 1
+      #         fi
+      #       fi
+      #     done
 
       - name: Rollback Migration on Failure
         if: failure()
@@ -241,6 +241,7 @@ jobs:
           DIRTY_STATE=$(psql ${POSTGRESQL_URL} -t -c "SELECT dirty FROM schema_migrations WHERE dirty = true LIMIT 1")
           if [[ "$DIRTY_STATE" == "true" ]]; then
             echo "The database is in a dirty state!"
+            gcloud sql backups restore $BACKUP_ID --restore-instance=sheffessions-staging-postgresql
             exit 1
           else
             echo "The database is clean."
