testing pipes

diff --git a/.github/workflows/sheffessions-staging.yml b/.github/workflows/sheffessions-staging.yml
--- a/.github/workflows/sheffessions-staging.yml
+++ b/.github/workflows/sheffessions-staging.yml
@@ -70,7 +70,6 @@ jobs:
     runs-on: ubuntu-latest
     env:
       POSTGRESQL_PASSWORD_STAGING: ${{ secrets.POSTGRESQL_PASSWORD_STAGING }}
-      # POSTGRESQL_URL: postgres://postgres:${{ secrets.POSTGRESQL_PASSWORD_STAGING }}@localhost:5432/postgres?sslmode=disable&search_path=public
       POSTGRESQL_URL: postgres://postgres:${{ secrets.POSTGRESQL_PASSWORD_STAGING }}@localhost:5432/postgres?sslmode=disable
     steps:
       - name: Checkout code
@@ -87,7 +86,7 @@ jobs:
       - name: 'Use gcloud CLI'
         run: 'gcloud info'
 
-      - name: 'Check and Create PostgreSQL Instance on Cloud SQL if it does not exist'
+      - name: 'Check Instance on Cloud SQL exists and update db password'
         run: |
           INSTANCE_EXISTS=$(gcloud sql instances list --filter="name:sheffessions-staging-postgresql" --format="get(name)")
 
@@ -177,6 +176,23 @@ jobs:
         run: |
           echo "MIGRATIONS_LIST=$(ls db/migrations | sort | tr '\n' ';')" >> $GITHUB_ENV
 
+      # - name: Apply Migrations Iteratively Production
+      #   working-directory: ./backend/sheffessions_api
+      #   run: |
+      #     IFS=';' read -ra MIGRATIONS <<< "$MIGRATIONS_LIST"
+      #     for migration in "${MIGRATIONS[@]}"; do
+      #       # Only apply up migrations
+      #       if [[ $migration == *".up.sql" ]]; then
+      #         psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
+      #         migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
+      #         if [ $? -ne 0 ]; then
+      #           echo "Migration $migration failed. Rolling back..."
+      #           migrate -database ${POSTGRESQL_URL} -path db/migrations down 1
+      #           exit 1
+      #         fi
+      #       fi
+      #     done
+
       - name: Apply Migrations Iteratively
         working-directory: ./backend/sheffessions_api
         run: |
@@ -187,8 +203,8 @@ jobs:
               psql ${POSTGRESQL_URL} -t -c "SET search_path TO public;"
               migrate -database ${POSTGRESQL_URL} -path db/migrations up 1
               if [ $? -ne 0 ]; then
-                echo "Migration $migration failed. Rolling back..."
-                migrate -database ${POSTGRESQL_URL} -path db/migrations down 1
+                echo "Migration $migration failed. Resetting the database..."
+                gcloud sql backups restore $BACKUP_ID --restore-instance=sheffessions-staging-postgresql
                 exit 1
               fi
             fi
