+

diff --git a/.github/workflows/sheffessions.yml b/.github/workflows/sheffessions.yml
--- a/.github/workflows/sheffessions.yml
+++ b/.github/workflows/sheffessions.yml
@@ -81,49 +81,50 @@ jobs:
           docker push europe-docker.pkg.dev/sheffessions/sheffessions-docker-repository/sheffessions_fe:sheffessions_fe-${{ steps.generate_tag.outputs.image_tag_sheffessions_fe }}
 
   production-database-migrations:
+    runs-on: ubuntu-latest
     needs: [
       production-build-sheffessions_api,
       production-build-sheffessions_fe
     ]
-    runs-on: ubuntu-latest
-    - name: 'Install Migrate CLI'
-      run: |
-        curl -L -o migrate.linux-amd64.tar.gz https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
-        CHECKSUM="b92fe73d3fc9ea2bd1e02c5b7840c16268e78956c0c05f6bdb90a78c42637020"
-        echo "$CHECKSUM  migrate.linux-amd64.tar.gz" | sha256sum --check
-        if [[ $? -ne 0 ]]; then
-          echo "Checksum verification failed!"
-          exit 1
-        fi
-        tar xvz -f migrate.linux-amd64.tar.gz
-        mv migrate.linux-amd64 /usr/local/bin/migrate
-
-    - name: Backup PostgreSQL Database
-      run: |
-        TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)  # store current UTC timestamp
-        gcloud sql backups create --instance=sheffessions-postgresql
-        echo "BACKUP_TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
-
-    - name: List Backups for PostgreSQL Database
-      run: |
-        RETRY_COUNT=0
-        MAX_RETRIES=5
-        SLEEP_DURATION=30
-        while [[ -z "$BACKUP_ID" && $RETRY_COUNT -lt $MAX_RETRIES ]]; do
-          BACKUP_ID=$(gcloud sql backups list --instance=sheffessions-postgresql --filter="startTime>'$BACKUP_TIMESTAMP'" --sort-by="~creationTimestamp" --limit=1 --format="get(id)")
-          if [[ -z "$BACKUP_ID" ]]; then
-            echo "Backup not found for attempt $((RETRY_COUNT+1)). Retrying in $SLEEP_DURATION seconds..."
-            sleep $SLEEP_DURATION
-            ((RETRY_COUNT++))
+    steps:
+      - name: 'Install Migrate CLI'
+        run: |
+          curl -L -o migrate.linux-amd64.tar.gz https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
+          CHECKSUM="b92fe73d3fc9ea2bd1e02c5b7840c16268e78956c0c05f6bdb90a78c42637020"
+          echo "$CHECKSUM  migrate.linux-amd64.tar.gz" | sha256sum --check
+          if [[ $? -ne 0 ]]; then
+            echo "Checksum verification failed!"
+            exit 1
           fi
-        done
+          tar xvz -f migrate.linux-amd64.tar.gz
+          mv migrate.linux-amd64 /usr/local/bin/migrate
 
-        if [[ -z "$BACKUP_ID" ]]; then
-          echo "Error: No backup found that was created after $BACKUP_TIMESTAMP after $MAX_RETRIES attempts"
-          exit 1
-        fi
+      - name: Backup PostgreSQL Database
+        run: |
+          TIMESTAMP=$(date --utc +%Y-%m-%dT%H:%M:%SZ)  # store current UTC timestamp
+          gcloud sql backups create --instance=sheffessions-postgresql
+          echo "BACKUP_TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
 
-        echo "BACKUP_ID=$BACKUP_ID" >> $GITHUB_ENV
+      - name: List Backups for PostgreSQL Database
+        run: |
+          RETRY_COUNT=0
+          MAX_RETRIES=5
+          SLEEP_DURATION=30
+          while [[ -z "$BACKUP_ID" && $RETRY_COUNT -lt $MAX_RETRIES ]]; do
+            BACKUP_ID=$(gcloud sql backups list --instance=sheffessions-postgresql --filter="startTime>'$BACKUP_TIMESTAMP'" --sort-by="~creationTimestamp" --limit=1 --format="get(id)")
+            if [[ -z "$BACKUP_ID" ]]; then
+              echo "Backup not found for attempt $((RETRY_COUNT+1)). Retrying in $SLEEP_DURATION seconds..."
+              sleep $SLEEP_DURATION
+              ((RETRY_COUNT++))
+            fi
+          done
+
+          if [[ -z "$BACKUP_ID" ]]; then
+            echo "Error: No backup found that was created after $BACKUP_TIMESTAMP after $MAX_RETRIES attempts"
+            exit 1
+          fi
+
+          echo "BACKUP_ID=$BACKUP_ID" >> $GITHUB_ENV
 
     - name: List Migrations
       working-directory: ./backend/sheffessions_api
